[tool.poetry]
name = "iotaiclass"
version = "0.1.0"
description = ""
authors = ["Tanakorn Youngmeesuk <phon.youngmeesuk@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
